name: CI Pipeline

on:
  push:
    branches:
      - '**'    # Run on pushes to any branch
  pull_request:
    branches:
      - '**'    # Run on pull requests to any branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use a Linux environment for the workflow

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Use Java 17 for building the Spring Boot application

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          tasks: "assemble"  # Gradle build task

      - name: Test Project
        run: ./gradlew test  # Run the tests using Gradle
